#!/bin/bash


echo "!! Pikabu Premium!!"

echo "!! Suscribe te a mi canal para que no te !!"
echo "!! pierdas ningunos de mis vídeos. !!"
echo "!! https://youtube.com/jonaiphone !!"

echo "!!  JONAIPHONE  📲 !!"


echo "!!  JONAIPHONE  📲 !!"


echo "!!  JONAIPHONE  📲 !!"
